name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_CREDENTIALS}}
        project_id: chatpdfapp

    - name: Configure Docker for GCR
      run: gcloud auth configure-docker

    - name: Build Docker image
      run: |
        docker build -t gcr.io/chatpdfapp/491ef3c3f8b2:${{ github.sha }} .
        docker push gcr.io/chatpdfapp/491ef3c3f8b2:${{ github.sha }}

    - name: Deploy to GKE
      run: |
        gcloud container clusters get-credentials chatpdf-cluster --zone us-west4 --project chatpdfapp
        kubectl set image deployment/my-app my-app=gcr.io/chatpdfapp/491ef3c3f8b2:${{ github.sha }}
        kubectl rollout status deployment/my-app
